/* Every genre here must exist as a tag in data.js, and every tag in data.js must
   appear here — otherwise a title becomes unreachable by filtering. The test
   suite asserts both directions. */
export default {
  anime: [
    { id: 'action', label: 'Action' },
    { id: 'adventure', label: 'Adventure' },
    { id: 'fantasy', label: 'Fantasy' },
    { id: 'scifi', label: 'Sci-Fi' },
    { id: 'mecha', label: 'Mecha' },
    { id: 'drama', label: 'Drama' },
    { id: 'thriller', label: 'Thriller' },
    { id: 'psychological', label: 'Psychological' },
    { id: 'mystery', label: 'Mystery' },
    { id: 'horror', label: 'Horror' },
    { id: 'comedy', label: 'Comedy' },
    { id: 'romance', label: 'Romance' },
    { id: 'sports', label: 'Sports' },
    { id: 'music', label: 'Music' },
    { id: 'historical', label: 'Historical' },
  ],
  games: [
    { id: 'rpg', label: 'RPG' },
    { id: 'action', label: 'Action' },
    { id: 'adventure', label: 'Adventure' },
    { id: 'openworld', label: 'Open World' },
    { id: 'fps', label: 'FPS' },
    { id: 'soulslike', label: 'Souls-like' },
    { id: 'strategy', label: 'Strategy' },
    { id: 'rts', label: 'RTS' },
    { id: 'simulation', label: 'Simulation' },
    { id: 'sandbox', label: 'Sandbox' },
    { id: 'survival', label: 'Survival' },
    { id: 'roguelite', label: 'Roguelite' },
    { id: 'platformer', label: 'Platformer' },
    { id: 'puzzle', label: 'Puzzle' },
    { id: 'indie', label: 'Indie' },
    { id: 'horror', label: 'Horror' },
    { id: 'thriller', label: 'Thriller' },
    { id: 'mystery', label: 'Mystery' },
    { id: 'psychological', label: 'Psychological' },
    { id: 'scifi', label: 'Sci-Fi' },
    { id: 'fantasy', label: 'Fantasy' },
    { id: 'historical', label: 'Historical' },
    { id: 'drama', label: 'Drama' },
    { id: 'comedy', label: 'Comedy' },
  ],
  statusLabels: {
    anime: [
      { id: 'all', label: 'All' },
      { id: 'watched', label: 'Watched' },
      { id: 'watching', label: 'Watching' },
      { id: 'plan', label: 'Plan to Watch' },
      { id: 'dropped', label: 'Dropped' },
    ],
    games: [
      { id: 'all', label: 'All' },
      { id: 'watched', label: 'Played' },
      { id: 'watching', label: 'Playing' },
      { id: 'plan', label: 'Plan to Play' },
      { id: 'dropped', label: 'Dropped' },
    ],
  },
};
